package dbtest

import (
	"context"
	"regexp"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/yerassyldanay/xchats/backend/internal/dbx"
)

// These tests read the migrated catalog on whichever engine is under test and prove the
// schema is engine-neutral in effect: the same portable types, nothing generated by the
// database, and nothing installed on the server beyond tables, indexes and views.

type catalogColumn struct {
	table, name, typ string
	dflt             *string
}

func (c catalogColumn) String() string { return c.table + "." + c.name }

// catalogColumns lists every column of every base table (views and the runner's own
// schema_migrations excluded) with its effective type and default expression.
func catalogColumns(t *testing.T, db *dbx.DB) []catalogColumn {
	t.Helper()
	query := `SELECT m.name, c.name, lower(c.type), c.dflt_value
		FROM sqlite_master m JOIN pragma_table_info(m.name) c
		WHERE m.type = 'table' AND m.name NOT LIKE 'sqlite_%' AND m.name <> 'schema_migrations'
		ORDER BY m.name, c.cid`
	if db.Dialect() == dbx.Postgres {
		query = `SELECT c.table_name, c.column_name, lower(c.data_type), c.column_default
			FROM information_schema.columns c
			JOIN information_schema.tables t ON t.table_schema = c.table_schema AND t.table_name = c.table_name
			WHERE c.table_schema = current_schema() AND t.table_type = 'BASE TABLE' AND c.table_name <> 'schema_migrations'
			ORDER BY c.table_name, c.ordinal_position`
	}
	rows, err := db.Query(context.Background(), query)
	if err != nil {
		t.Fatalf("read catalog columns: %v", err)
	}
	defer rows.Close()
	var out []catalogColumn
	for rows.Next() {
		var c catalogColumn
		if err := rows.Scan(&c.table, &c.name, &c.typ, &c.dflt); err != nil {
			t.Fatal(err)
		}
		out = append(out, c)
	}
	if err := rows.Err(); err != nil {
		t.Fatal(err)
	}
	if len(out) == 0 {
		t.Fatal("catalog returned no columns — is the schema migrated?")
	}
	return out
}

// portableTypes is the whole type vocabulary of the schema, in the spelling each engine's
// catalog reports. TEXT carries ids, JSON documents and e-mail; BIGINT carries UTC Unix
// milliseconds; BYTEA carries encrypted secrets (SQLite accepts the name and stores bytes).
var portableTypes = []string{"text", "bigint", "integer", "boolean", "bytea", "numeric", "real"}

func TestSchemaColumnsUsePortableTypes(t *testing.T) {
	db := OpenRaw(t)
	for _, c := range catalogColumns(t, db) {
		if !slices.Contains(portableTypes, c.typ) {
			t.Errorf("%s has type %q; the schema allows only %v", c, c.typ, portableTypes)
		}
	}
}

var generatedDefault = regexp.MustCompile(`(?i)now|clock_timestamp|current_(timestamp|date|time)|gen_random_uuid|uuid_generate|nextval|strftime|datetime|randomblob`)

func TestSchemaHasNoDatabaseGeneratedValues(t *testing.T) {
	db := OpenRaw(t)
	ctx := context.Background()
	idTables := 0
	for _, c := range catalogColumns(t, db) {
		if c.dflt != nil && generatedDefault.MatchString(*c.dflt) {
			t.Errorf("%s defaults to %s: ids and times are bound by Go, never generated by the database", c, *c.dflt)
		}
		if strings.HasSuffix(c.name, "_at") || strings.HasSuffix(c.name, "_ts") {
			if c.typ != "bigint" {
				t.Errorf("%s is %s, want bigint (UTC Unix milliseconds)", c, c.typ)
			}
			if c.dflt != nil {
				t.Errorf("%s has default %s; the caller supplies every timestamp", c, *c.dflt)
			}
		}
		if c.name == "id" {
			pk := sqlitePrimaryKey(t, db, ctx, c.table)
			if len(pk) == 1 && pk[0] == "id" {
				idTables++
				if c.typ != "text" {
					t.Errorf("%s is %s, want text (a UUID string supplied by Go)", c, c.typ)
				}
				if c.dflt != nil {
					t.Errorf("%s has default %s; the caller supplies every id", c, *c.dflt)
				}
			}
		}
	}
	if idTables < 40 {
		t.Errorf("only %d tables have an id primary key; the catalog read looks wrong", idTables)
	}
}

func TestSchemaHasNoServerSideObjects(t *testing.T) {
	db := OpenRaw(t)
	ctx := context.Background()
	count := func(query string) int {
		t.Helper()
		var n int
		if err := db.QueryRow(ctx, query).Scan(&n); err != nil {
			t.Fatalf("%s: %v", query, err)
		}
		return n
	}
	if db.Dialect() == dbx.Postgres {
		const inSchema = `(SELECT oid FROM pg_namespace WHERE nspname = current_schema())`
		if n := count(`SELECT count(*) FROM pg_proc WHERE pronamespace = ` + inSchema); n != 0 {
			t.Errorf("%d user-defined functions in the schema; the migrations must not create any", n)
		}
		if n := count(`SELECT count(*) FROM information_schema.sequences WHERE sequence_schema = current_schema()`); n != 0 {
			t.Errorf("%d sequences in the schema; ids are Go-generated text", n)
		}
		if n := count(`SELECT count(*) FROM pg_trigger tg JOIN pg_class c ON c.oid = tg.tgrelid
			WHERE c.relnamespace = ` + inSchema + ` AND NOT tg.tgisinternal`); n != 0 {
			t.Errorf("%d triggers in the schema; the migrations must not create any", n)
		}
		if n := count(`SELECT count(*) FROM information_schema.columns
			WHERE table_schema = current_schema() AND data_type = 'USER-DEFINED'`); n != 0 {
			t.Errorf("%d columns use an extension or custom type", n)
		}
		return
	}
	if n := count(`SELECT count(*) FROM sqlite_master WHERE type = 'trigger'`); n != 0 {
		t.Errorf("%d triggers in the schema; the migrations must not create any", n)
	}
}

// The seed rows are the one place the migration itself writes timestamps: literal Unix
// milliseconds for 2026-10-06T00:00:00Z, which must read back as that instant.
func TestSeedTimestampsAreUnixMillis(t *testing.T) {
	db := OpenRaw(t)
	var created, joined time.Time
	if err := db.QueryRow(context.Background(), `SELECT o.created_at, ou.joined_at
		FROM organizations o JOIN organization_users ou ON ou.organization_id = o.id
		WHERE o.id = '00000000-0000-0000-0000-000000000001'`).Scan(&created, &joined); err != nil {
		t.Fatal(err)
	}
	want := time.Date(2026, 10, 6, 0, 0, 0, 0, time.UTC)
	if !created.Equal(want) || !joined.Equal(want) {
		t.Errorf("seeded created_at/joined_at = %v / %v, want %v", created, joined, want)
	}
}
